version: '2'
services:
  neo4j:
    build:
      context: .
      dockerfile: neo4j/Dockerfile
    container_name: tutorial_neo4j_plus_apoc
    env_file:
      - .env
    environment:
      - dbms.memory.heap.initial_size=2048
      - NEO4J_HEAP_MEMORY=7000
      - NEO4J_CACHE_MEMORY=1G
      - NEO4J_dbms_memory_heap_maxSize=4096
    cap_add:
      - SYS_RESOURCE
    ports:
      - "7474:7474"
    expose:
      - "7687"
    labels:
      - "description=Frederik's Neo4J graph database server, including APOC library"

  neo4jloader:
    build:
      context: .
      dockerfile: neo4jloader/Dockerfile
    env_file:
      - .env
    container_name: tutorial_neo4jloader
    links:
      - neo4j
